export enum ACTIONS {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  ADD_TRACKS = 'ADD_TRACKS',
  HANDLE_OPEN = 'HANDLE_OPEN',
  NOTIFY = 'NOTIFY',
  CREATE_PLAYLIST = 'CREATE_PLAYLIST',
  REMOVE_PLAYLIST = 'REMOVE_PLAYLIST',
  ADD_TRACK_TO_PLAYLIST = 'ADD_TRACK_TO_PLAYLIST',
  REMOVE_TRACK_FROM_PLAYLIST = 'REMOVE_TRACK_FROM_PLAYLIST',
}
export type STORE_ACTION_TYPES =
  | UserAction
  | PlaylistItemAction
  | TrackAction
  | UtilsAction
  | PlaylistTrackAction;
